### ISSUE TITLE
until_date in gathertw.sh

### ISSUE THREAD

**Issue by ifujisawa** [ShellShoccar-jpn/kotoriotoko#9]
Thanks for great job, which enable us to collect twitter so easily.

In that script, there are two options until_date and since_date.
Why does not until_date allow to specify time, though since_date does?
Is there any technical difficulties?

**Comment by colrichie** [comment]
@ifujisawa, Thank you for using our application.

Correct. `until_date` option can't accept the time part "HH:MM:SS." That is because `until_date` depends on the endpoint ["GET search/tweets"](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets), and it can pick up the same or older tweets only in date unit with `until` parameter. On the other hand, `since_date` option works by the shell script "gathertw.sh" itself. `gathertw.sh` can filter the same or later tweets by checking the timestamps of the tweets, which the above endpoint has returned.

Do you follow me?

**Comment by ifujisawa** [comment]
Thank you for clear explanation. I got it.
